### ISSUE TITLE
Implement Light Mode

### ISSUE THREAD

**Issue by JJTech0130** [donno2048/running-cat#4]
When in Windows Light Mode, the cat is invisible.
![image](https://user-images.githubusercontent.com/53275876/156068495-6a37ecb5-57bd-4afd-8b36-ac072ede8cbe.png)

**Comment by donno2048** [comment]
Thanks for the report. Instead of checking for system themes in the code we could simply make the contours of the cat darker and maybe wider, this will solve not only the problem for different themes, but also eliminate it for **every** custom taskbar color palette which is a lot harder to determine whether is "light" or "dark". What do you think?

**Comment by JJTech0130** [comment]
Sure! That sounds better... I completely forgot about custom taskbar colors.

**Comment by donno2048** [comment]
Solved [5651dc2](https://github.com/donno2048/running-cat/commit/5651dc2f86343076ef80079a424b6b358d8b5751)
